# Generated by Django 4.2.1 on 2023-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('bdate', models.DateField()),
                ('gpa', models.FloatField()),
                ('gender', models.CharField(default='Male', max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('department', models.CharField(choices=[('General', 'General'), ('Computer Science', 'Computer Science'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Information Technology', 'Information Technology'), ('Cyber Security', 'Cyber Security'), ('Data Science', 'Data Science')], default='General', max_length=50)),
                ('picture', models.ImageField(default='static/img/default pp.png', null=True, upload_to='photos/%y/%m/%d')),
                ('id', models.IntegerField(default=20230000, primary_key=True, serialize=False)),
            ],
        ),
    ]
